language: java

matrix:
   include:
      - jdk: openjdk8
      - jdk: openjdk9
      - os: osx
        osx_image: xcode10.1

# skip installation step
install: true

script: 
  - cd myproject 
  - mvn clean verify

cache:
   directories:
      - $HOME/.m2