language: java

matrix:
   include:
      #always build this environment
      - jdk: openjdk8
        env: ADDITIONAL_MAVEN_ARGS="-Pjacoco coveralls:report"
      #only on PR
      - jdk: openjdk9
        if: type IN (pull_request)
      #only on PR
      - os: osx
        osx_image: xcode10.1
        if: type IN (pull_request)

# skip installation step
install: true

script: 
  - cd myproject 
  - mvn clean verify $ADDITIONAL_MAVEN_ARGS

cache:
   directories:
      - $HOME/.m2
